// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdjSSv_Rvx8uixrF3fqo5LVbHyGOAXRZE',
    appId: '1:898315864585:web:d9d2fc91989bc3123706d8',
    messagingSenderId: '898315864585',
    projectId: 'healthtimer-9acef',
    authDomain: 'healthtimer-9acef.firebaseapp.com',
    storageBucket: 'healthtimer-9acef.firebasestorage.app',
    measurementId: 'G-SS8X61T0HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1BbfIcKf8BdYP-GEXxh2NSop8B4ypIA',
    appId: '1:898315864585:android:fa77a930027f0f093706d8',
    messagingSenderId: '898315864585',
    projectId: 'healthtimer-9acef',
    storageBucket: 'healthtimer-9acef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZtDpCOXktQxwGUkcVfiKHNPL56fT980',
    appId: '1:898315864585:ios:d1bbf18957eeeda23706d8',
    messagingSenderId: '898315864585',
    projectId: 'healthtimer-9acef',
    storageBucket: 'healthtimer-9acef.firebasestorage.app',
    androidClientId: '898315864585-prmiqo0q6r7728qgom71ust9tsnh75k8.apps.googleusercontent.com',
    iosClientId: '898315864585-u7upf6l2cfraerdvutao82n78hcla8le.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ZtDpCOXktQxwGUkcVfiKHNPL56fT980',
    appId: '1:898315864585:ios:d1bbf18957eeeda23706d8',
    messagingSenderId: '898315864585',
    projectId: 'healthtimer-9acef',
    storageBucket: 'healthtimer-9acef.firebasestorage.app',
    androidClientId: '898315864585-prmiqo0q6r7728qgom71ust9tsnh75k8.apps.googleusercontent.com',
    iosClientId: '898315864585-u7upf6l2cfraerdvutao82n78hcla8le.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdjSSv_Rvx8uixrF3fqo5LVbHyGOAXRZE',
    appId: '1:898315864585:web:f530c6666a05b16d3706d8',
    messagingSenderId: '898315864585',
    projectId: 'healthtimer-9acef',
    authDomain: 'healthtimer-9acef.firebaseapp.com',
    storageBucket: 'healthtimer-9acef.firebasestorage.app',
    measurementId: 'G-XXDCND2TQ3',
  );

}